### ISSUE TITLE
Using gmessage in docker, models do not download

### ISSUE THREAD

**Issue by x3ek** [drbh/gmessage#3]
I've started gmessage in Docker Desktop (Windows 10 Host / Linux Containers) and it appears to run normally. Here's how I ran message: 
```ps
docker run -d -p 10999:10999 -v C:\Users\Xeek\gpt4all-models:/.cache/gpt4all --name gmessage drbh/gmessage:v0.0.0
```
When I get into the web frontend I see this:
![image](https://github.com/drbh/gmessage/assets/6032840/5717d5be-dac5-4b4d-b620-ccf35e8278be)
I'll click "Download First", and then monitor the file in the cache, it's a bin file and it remains at 0KB and no network activity results. It doesn't appear to be downloading models. I would just copy in some models I've manually downloaded, but these are bin files. I have no idea what format this is in as it will not use downloaded models if renamed to the bin extension. Here's the docker log:
```
2024-01-15 19:24:33 GUI binary not found, skipping...
2024-01-15 19:24:33 Database path: //.cache/gmessage/database.db
2024-01-15 19:24:33 Model configuration: map[]
2024-01-15 19:24:33 Listening on port 10999
2024-01-15 19:24:33 
2024-01-15 19:24:33  ┌───────────────────────────────────────────────────┐ 
2024-01-15 19:24:33  │                   Fiber v2.45.0                   │ 
2024-01-15 19:24:33  │              http://127.0.0.1:10999               │ 
2024-01-15 19:24:33  │      (bound on host 0.0.0.0 and port 10999)       │ 
2024-01-15 19:24:33  │                                                   │ 
2024-01-15 19:24:33  │ Handlers ............ 23  Processes ........... 1 │ 
2024-01-15 19:24:33  │ Prefork ....... Disabled  PID ................. 1 │ 
2024-01-15 19:24:33  └───────────────────────────────────────────────────┘ 
2024-01-15 19:24:33 
2024-01-15 19:24:41 Model to download: https://gpt4all.io/models/ggml-gpt4all-l13b-snoozy.bin
2024-01-15 19:24:51 Model: .cache/gpt4all/ggml-gpt4all-l13b-snoozy.bin
2024-01-15 19:24:51 mpt_model_load: loading model from '//.cache/gpt4all/ggml-gpt4all-l13b-snoozy.bin' - please wait ...
2024-01-15 19:24:51 mpt_model_load: invalid model file '//.cache/gpt4all/ggml-gpt4all-l13b-snoozy.bin' (bad magic)
```
I can wait for some time, that file will not increase in size.

**Comment by x3ek** [comment]
I found the bin file download URI and downloaded it manually and put it in the .cache/gpt4all/ folder and I get further, but my chat just gets stuck with "thinking" and doesn't work, likely because of these errors:
```
2024-01-15 19:31:42 Model: .cache/gpt4all/ggml-gpt4all-l13b-snoozy.bin
2024-01-15 19:26:14 GPT-J ERROR: failed to load model from //.cache/gpt4all/ggml-gpt4all-l13b-snoozy.bin2024-01-16T01:31:42.938341777Z mpt_model_load: invalid model file '//.cache/gpt4all/ggml-gpt4all-l13b-snoozy.bin' (bad magic)
2024-01-15 19:31:42 mpt_model_load: loading model from '//.cache/gpt4all/ggml-gpt4all-l13b-snoozy.bin' - please wait ...
2024-01-15 19:32:11 MODEL 0xc000014290
2024-01-15 19:32:11 MODEL <nil>
2024-01-15 19:32:11 GPT-J ERROR: failed to load model from //.cache/gpt4all/ggml-gpt4all-l13b-snoozy.binpanic: runtime error: invalid memory address or nil pointer dereference
2024-01-15 19:32:11 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9048d8]
2024-01-15 19:32:11 
2024-01-15 19:32:11 goroutine 55 [running]:
2024-01-15 19:32:11 github.com/nomic-ai/gpt4all/gpt4all-bindings/golang.(*Model).SetTokenCallback(...)
2024-01-15 19:32:11     /app/cmd/server/vendors/gpt4all-bindings/golang/gpt4all.go:82
2024-01-15 19:32:11 main.StreamCompletion.func1(0xc000310180)
2024-01-15 19:32:11     /app/cmd/server/routes.go:368 +0xb8
2024-01-15 19:32:11 github.com/valyala/fasthttp.NewStreamReader.func1()
2024-01-15 19:32:11     /root/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/stream.go:44 +0x38
2024-01-15 19:32:11 created by github.com/valyala/fasthttp.NewStreamReader
2024-01-15 19:32:11     /root/go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/stream.go:43 +0x37c
```

**Comment by JuanjoJimGil** [comment]
I'm having the same issue. I'm working on a Mac and I can't even locate the folder to put the model in.
